version: '3.8'

services:
  bokeh-app:
    container_name: bokeh-visualizer
    build: .
    ports:
      - "5007:5007"
    command: >
      bokeh serve second_screen_fileinput.py
      --allow-websocket-origin=*
      --port=5006
      --websocket-max-message-size=1073741824
